# Weapons

# rightClicks
item replace entity @s hotbar.1 with carrot_on_a_stick{display:{Name:'{"text":"Annihilating Flame","color":"red","bold":true}',Lore:['{"text":"Channeling, Damage","color":"dark_gray"}','{"text":" "}','{"text":"Channels for a short duration before performing","color":"gray"}','{"text":"a flurry of strikes in front for several seconds,","color":"gray"}','{"text":"continuously damaging enemies hit by each strike.","color":"gray"}','{"text":" "}','[{"text":"Damage per Strike: ","color":"gold","bold":true},{"text":"4","color":"white","bold":false}]','[{"text":"Channeling Time: ","color":"blue","bold":true},{"text":"1.7","color":"white","bold":false}]','[{"text":"Duration: ","color":"aqua","bold":true},{"text":"2","color":"white","bold":false}]','[{"text":"Cooldown: ","color":"light_purple","bold":true},{"text":"15","color":"white","bold":false}]']},flurry:1} 1

item replace entity @s hotbar.2 with carrot_on_a_stick{display:{Name:'{"text":"Ashfall","color":"red","bold":true}',Lore:['{"text":"Channeling, Movement, Damage","color":"dark_gray"}','{"text":" "}','{"text":"Levitates into the air and powers up before","color":"gray"}','{"text":"slamming into the ground, damaging and slowing","color":"gray"}','{"text":"enemies caught in the area. Deals higher damage","color":"gray"}','{"text":"when hitting enemies close to the center.","color":"gray"}','{"text":" "}','{"text":"When cast mid-air, the levitation effect will not occur.","color":"dark_gray","bold":false,"italic":true}','{"text":" "}','[{"text":"Max Damage: ","color":"gold","bold":true},{"text":"6","color":"white","bold":false}]','[{"text":"Channeling Time: ","color":"blue","bold":true},{"text":"1.2","color":"white","bold":false}]','[{"text":"Max Slow: ","color":"green","bold":true},{"text":"90%","color":"white","bold":false}]','[{"text":"Cooldown: ","color":"light_purple","bold":true},{"text":"7","color":"white","bold":false}]']},slam:1} 1

item replace entity @s hotbar.3 with carrot_on_a_stick{display:{Name:'{"text":"Flame Dash","color":"red","bold":true}',Lore:['{"text":"Movement","color":"dark_gray"}','{"text":" "}','{"text":"Leaps a great distance into the target direction.","color":"gray"}','{"text":" ","color":"gray"}','{"text":"Can be used during the channeling of Annihilating Flame and Ashfall.","color":"dark_gray","bold":false,"italic":true}','{"text":" "}','{"text":"When used during the effect of Annihilating Flame, the effect of","color":"dark_gray","bold":false,"italic":true}','{"text":"Annihilating Flame is canceled.","color":"dark_gray","bold":false,"italic":true}','{"text":" "}','[{"text":"Cooldown: ","color":"light_purple","bold":true},{"text":"4","color":"white","bold":false}]']},leap:1} 1

# Armour
item replace entity @s armor.head with player_head{display:{Name:'{"text":"Herald of Ash","color":"red","bold":true}',Lore:['{"text":"Bring scorched earth.","color":"dark_gray"}']},AttributeModifiers:[{AttributeName:"generic.movement_speed",Name:"generic.movement_speed",Amount:0.25,Operation:1,UUID:[I;-1724249424,-1455733257,-1424099220,-2112264031],Slot:"head"}],SkullOwner:{Id:[I;90631028,437994261,-1903946005,1293148022],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGM2ZGYwMjllNGFiYjUwMzg3Y2JmNDEwOGZmYjUxYjVmYzI1ZjY0Y2VmMzc0NTI2MTEyNTU0Nzc5ZDJkNWE5YSJ9fX0="}]}}} 1
item replace entity @s armor.legs with netherite_leggings{display:{Name:'{"text":"Crimson Guards","color":"red","bold":true}',Lore:['{"text":"Witness the fire burn.","color":"dark_gray"}']},HideFlags:133,Enchantments:[{id:"minecraft:fire_protection",lvl:1s},{id:"minecraft:blast_protection",lvl:1s},{id:"minecraft:unbreaking",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:6,Operation:0,UUID:[I;1300187898,-1024242576,-1679771833,-1654329577],Slot:"legs"}],Trim:{material:"minecraft:redstone",pattern:"minecraft:dune"}} 1
item replace entity @s armor.feet with netherite_boots{display:{Name:'{"text":"Magma Striders","color":"red","bold":true}',Lore:['{"text":"Travel through the fire and the flames.","color":"dark_gray","bold":false}','{"text":" "}','{"text":"Reduces fall damage significantly.","color":"dark_purple"}']},HideFlags:133,Unbreakable:1b,Enchantments:[{id:"minecraft:feather_falling",lvl:10s},{id:"minecraft:unbreaking",lvl:1s}],Trim:{material:"minecraft:gold",pattern:"minecraft:wild"}} 1