#CONJURE READY
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 0 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" None","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 5 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Manipulate Earth","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 13 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Frostball","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 23 if score @s cclashCasted matches 1 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Pyroball","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 10 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Rolling Boulder","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 26 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Flight","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 46 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Flame Flash","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 18 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Exhiliration","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 36 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Sonic","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 28 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Armor of Earth","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 15 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Earthquake","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 39 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Freezing Beam","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 69 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Strike of Lightning","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 23 if score @s cclashCasted matches 3 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Ice Spikes","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 49 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Glacier Mend","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 51 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Meteor","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 33 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Split Earth","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 31 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Prison of Ice","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 59 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Magma Floor","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s if score @s cclashCooldown matches 0 if score @s cclashSpell matches 41 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"text":"READY","bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Arctic Erruption","bold":true,"color":"white"}]

#CONJURE ON COOLDOWN
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 0 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" None ","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 5 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Manipulate Earth","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 13 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Frostball","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 23 if score @s cclashCasted matches 1 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Pyroball","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 10 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Rolling Boulder","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 26 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Flight","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 46 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Flame Flash","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 18 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Exhiliration","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 36 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Sonic","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 28 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Armor of Earth","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 15 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Earthquake","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 39 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Freezing Beam","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 69 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Strike of Lightning","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 23 if score @s cclashCasted matches 3 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Ice Spikes","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 49 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Glacier Mend","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 51 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Meteor","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 33 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Split Earth","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 31 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Prison of Ice","bold":true,"color":"white"}]
execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 59 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Magma Floor","bold":true,"color":"white"}]

execute as @a[tag=cclashPlaying] at @s unless score @s cclashCooldown matches 0 if score @s cclashSpell matches 41 run title @s actionbar ["",{"text":"Conjure Cooldown: ","color":"aqua"},{"score":{"name":"@s","objective":"cclashCooldown"},"bold":true,"color":"white"},{"text":" | ","bold":true,"color":"aqua"},{"text":"Current Spell:","color":"aqua"},{"text":" Arctic Erruption","bold":true,"color":"white"}]